language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install ."
  - "pip install -q flake8"

# command to run tests
script:
  - python -m unittest discover
  - flake8 --version
  - flake8 --ignore E501 .

branches:
    only:
        - master

notifications:
email: false
